api_list = {
    'accounts/send_phone/': 'The user enters the phone number for validation',
    'accounts/valid_phone/<int:pk>': 'The user enters the validation code',
    'accounts/register/<str:status>/<int:pk>': 'The user fills the registration form.',
    'accounts/login/': 'The user login.',
    'accounts/changepassword/': 'The user change password.',
    'accounts/profile/': 'View user information',
    'accounts/logout/': 'The user log out.',
    'accounts/delete_account/': 'The user delete account.',
    
    'accounts/send_request/<int:pk>': 'The user requests to follow another.',   
    'accounts/accept_request/<int:pk>/<str:status>': 'The user accepts another request.',   
    'accounts/request_list/': 'The user sees all requests.',
    'accounts/follower_list/': 'The user sees all followers.',
    'accounts/follower_list/<int:pk>': 'The user sees a follower profile.',
    'accounts/following_list/<int:pk>': 'The user sees all followings.',
    'accounts/following_list/': 'The user sees a following profile.',
    'accounts/unfollow/<int:pk>': 'The user unfollow other user.',
    'accounts/block/<int:pk>': 'The user block other user.',
    'accounts/user_info/<int:pk>': 'The user sees other user informations.',
        
    'posts/posts': 'Show the user posts.',
    'posts/posts/<int:pk>': 'Show the other user posts.',
    'posts/single_post/<int:pk>': 'Show a single post.',
    'posts/new_post/': 'Add a new post.',
    'posts/update_post/<int:pk>': 'Update a post.',
    'posts/delete_post/<int:pk>': 'Delete a post.',
        
    'posts/create_comment/<int:pk>': 'Add a comment and get post id.',
    'posts/delete_comment/<int:pk>': 'delete a comment and get comment id.',
    'posts/reply_comment/<int:pk>': 'Reply a comment and get comment id.',
    'posts/delete_reply_comment/<int:pk>': 'Delete a Reply and get reply comment id.',
    
    'posts/like_post/<int:pk>': 'Like a post and get post id.',
    'posts/show_liker_post/<int:pk>': 'Show who like this post and get post id.',
    'posts/like_comment/<int:pk>': 'Like a comment and get comment id.',
    'posts/show_liker_comment/<int:pk>': 'Show who like this comment and get comment id.',
    'posts/like_reply/<int:pk>': 'Like reply comment.',
    'posts/show_liker_reply/<int:pk>': 'Show who like a reply comment and get reply comment id.',
    
    'posts/show_comments/<int:pk>': 'Show all comments and get post id.',
    
    'posts/bookmarck/<int:pk>': 'Add or delete post from bookmarck and get post id.',
    'posts/show_bookmarck/': 'Show bookmarck list .',
}
